eureka:
  appinfo:
    replicate:
      interval: 10
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    instanceInfoReplicationIntervalSeconds: 10

stores:
  ribbon:
    ServerListRefreshInterval: 1000

logging:
  level:
    org.salgar: INFO